### PR TITLE
New js

### PR DESCRIPTION
**Pull request by Sarahhagen2191**
Just uploads the css and js - Tarik send over

### CODE REVIEW

**Review by Sarahhagen2191 — COMMENTED** [review]
Add the new html as i think Tarik code wasn't in there I think forgot to do git pull main

**Review by Sarahhagen2191 — COMMENTED** [review]
Update the script and stylesheet link

**Review by kevmcgowan — APPROVED** [review]
Thank you Sarah

**Review by kevmcgowan — COMMENTED** [review]
merged

**Pull request merged**
